language: node_js
node_js:
  - "8"
  - "10"
os: osx
cache: cargo
before_install:
  - curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y
  - source $HOME/.cargo/env

script: |
  yarn --ignore-scripts && \
  yarn build

deploy:
  - provider: script
    script: node tools/upload.js
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file_glob: true
    file: dist/*.node
    skip_cleanup: true
    on:
      tags: true
