os: Visual Studio 2015

environment:
  GOOGLE_CLOUD_STORAGE_CONFIG_TOKEN:
    secure: w1yF6X7+S9SBAPfyPeNLTA==
  
  matrix:
    - BITS: 32
      ARC: "x86"
    - BITS: 64
      ARC: "x64"

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host "%ARCH%-pc-windows-msvc" --default-toolchain stable -y
  - SET PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -Vv
  - rustc --print cfg
  - yarn --ignore-scripts
  - ls

cache:
  - target

build_script:
  - ps: Install-Product node 8 $env:ARC
  - node -v
  - npm i -g npm
  - npm config set msvs_version 2015
  - npm i -g node-gyp
  - yarn --ignore-scripts
  - yarn build
  - node tools\appveyor-scripts.js
  - ps: Install-Product node 10 $env:ARC
  - node -v
  - npm i -g npm
  - npm config set msvs_version 2015
  - npm i -g node-gyp
  - yarn --ignore-scripts
  - yarn build
  - node tools\appveyor-scripts.js

after_test:
  - ls dist

artifacts:
  - path: dist\*.node
    name: Binary

before_deploy:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - appveyor-tools\secure-file -decrypt .\google-secret-file.json.enc -secret %GOOGLE_CLOUD_STORAGE_CONFIG_TOKEN%
  - SET GOOGLE_APPLICATION_CREDENTIALS=C:\projects\node-crypto\google-secret-file.json
  - node tools\upload.js

deploy:
  provider: GitHub
  description: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: WOwBw2Tzivslwkbev6rJfhZfUbcfRvENwqQZfRZBL5R6L+Cb0y2tv5lyobrZiWPq
  artifact: Binary
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true # deploy on tag push only